name: Release Obsidian plugin

on:
  push:
    tags:
      - '*'  # На любой пуш тега

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm ci

      - name: Build plugin
        run: npm run build

      - name: Create plugin zip
        run: |
          mkdir -p release
          cp dist/main.js manifest.json release/
          cd release
          zip plugin.zip main.js manifest.json

      - name: Create GitHub release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          gh release create "$TAG" \
            --title "$TAG" \
            --notes "Automated release for $TAG" \
            release/plugin.zip \
            release/main.js \
            release/manifest.json
